# Generated by Django 4.0.6 on 2022-07-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=201, null=True, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Cоздан'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=40, null=True, verbose_name='Название'),
        ),
    ]
