# Generated by Django 4.0.6 on 2022-07-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_anons_alter_articles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=35, null=True, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='Название'),
        ),
    ]
