# Generated by Django 4.0.6 on 2022-07-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_articles_anons_alter_articles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Фото'),
        ),
    ]
